language: scala

scala:
- 2.11.8

jdk:
- oraclejdk8

script: $TRAVIS_BUILD_DIR/travis/build.sh

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

env:
  global:
  - secure: o0NAGYmhpsKBDknZ0ltZE+sJZMmasJb6H0jcogFG1kan9Q1Hu/5uq/87u+Iv8eMfdQbFyKmGuaokbiCxCusD3ugaeHkCY8Rxvdi9BycH2wgk+E4AA0N6yesJp4DhLfutHB2P2scP3hnEcRECBJxe1pvo7NWV0Hqx8jEOs1IIKWtDO0p9cHYK2QkN33RdWUDnw8EYthezmb60Lmanxt00qWIkuONnbrY/4ES8Fca3mzFeBSsS24d688tyNzP8JF5KRpSbaXxgCZ/QGdxwQ6C+mr8qV/d6otLOR5TvnRr8rzt5eGP+jxOlYN5V3gnpj+OtzdMBrv7f2i9uEjdMXneQIbIrYurwP2VkdNTXeehkjtgBKR/DLvrN/esb5EcVMNkVVw1LZwiXwCj4HSOtI+IznG/UKljHwLx7Vsi/nbY3Xxc8ys5UMrdfBC5ZpoHfJ9EVbNOGlnRbop9gthClFV2/b22SPcouU6r3oloH81T8xdKT3Yqfvy0eYnqDDvjV49yIVFm5u8fLz1DpZ3pO4t3UWSug5/vW9lGOnKGKXnGqbYylfZWXnH7Cir70Nb4aplDpzOARzw8quE61hXR6s/qCe72Qo9k64dWrOmMyyp47wcoYYDmb9EcK0x3W39dZ87b/Pkapevr4HCGlssClzKd0uWzSqZOYVO3KFqMpTixwLXE=
  - secure: mfBaXns+qDFXVOQ+LVw1bohERBn4t54DfIzIsiogkHsBoic3C2SoB6L3RFoVOp7fDHrdYpvWs5jYDvp6maVMfSHSR2Jrcq7QAGY+G3D44CG7LlhuJj8sNMtWH3KtgALcLQKM96k6FWRKo4aSWlk9lI6WE2OW40V4uxwVUIHeZcMIseJwdRiTCoDui7FhHRQUij4blRbiJfDkfAmK80ODPT5cLqof34zpNBdihJBDErZJPI+a2SXSxJLouuDmiwfKlgrDMlOhA2ydugBv8JD1xo4RB+lfp/EHxeqRruhPjk3NHFy1EOZKAcz/ulkzzgr4Ic23I+0ybJVA6TYP2qC/KtgsiGgaZA7CyTt7dciUw44otKJ6SkCQQ9u/zjv2Wewh3LWUCZD1dARQQBQ69jhfi2bHxFnzm/eNx+Pfka5BbnyGa2XIs+BYk4UCNKi+3qZk63gJQjAWc/IZ2BNAlcMzIkwWHZp+rG3s8JUEkXae+esjlmbTSajb+pR/PiJRr3jGS3cacdzwutyAokCJVGfuGl4SHryLSvAiaELmCflXByuKY1c9NIt9Qk5Vai8spvTkdaZnIwbeYu+J/b490vSYMzWV5SohXX3GdhwcoBIQHFrXTtFT498/KkPWbPCFwkSGU1NAUcSSnMCrUs/PVsrFO6eBeFC5BS8ku4uOIs4IJ1Q=
  - secure: kYYzI2ymR1+a6q503WEzKPV4hZVzWzOfvUjK9GWHGGSMRCV7LvQVy8EtB02pF0SNn7lXeDfSvT6hQxRl5RcQWYeFx3WBPx8YVVBIfHJZ55Kc4VrWKh1VvrDznbLR19kvuiYHfT7QyPZz75VBXaDTGkjI8nUpmwU76ncyB504aAGtFrMUISiJBHs8KjmDj4WTIGBYL4a7VODufB5VSo6fi8L9QCHu0pgBgke4ILBGpRHZMArAxjfEpFHZ3MwiPMzUGvocLD8nbI0umLMc4EKiN+/61PlZdrFJf/IDzcbVD6JGgPEFuNq9pD/MupvL3jdN53oLvbpuxANliYXA07d7+ub28ARPqs+tUmFhJNTQqz/+MFA5wJ33meHJTm9vEoQrcGslfV1Y9kzQNqklQTEefbH2y0bDdCG14CfwmwhTgRvw99zCSWVUikCqdiFrpT6jY9QEWODFS4+ODjd3KwidwK/N1IVD6SLSmF6nwrVme5Hl90ss/HTFcLw7wE9myyovHyfDtoYZgXDLE55/swEVC33RzXAczTfqde1K5Y19w5VULIUe6cnvxv7OCf4fG3svxIPvXV12b3wfQnoiE9ulEJoxE3OeLkRI9uuh6NEkK51K4OvUXmdKCHvRwCr+X1Eyi4yX9QN6J6qNf8s8FlLit9WxROs0F75NbdlAYLmzT20=
